import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lilita_One } from "next/font/google";

import Providers from "./ProvidersWrapper";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const lilitaOne = Lilita_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-lilita-one",
});

export const metadata: Metadata = {
  title: "SmartQuiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en" className={`${lilitaOne.variable} ${inter.variable}`}>
        <body>{children}</body>
      </html>
    </Providers>
  );
}
