name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Or whatever version you're using

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: npx jest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.4
